logger:
  level: "debug"
  development: true

server:
  port: 8080

mongo:
  host: "mongo"
  port: 27017
  replica-set: rs0
  database: "category-query"
  migrations:
    enabled: true
    auto-migrate: true

kafka:
  brokers: "kafka:29092"
  schema-registry:
    url: "http://schema-registry:8081"
    auto-register-schemas: true
  consumers-config:
    default-group-id: "ecommerce-category-query-service"
    default-auto-offset-reset: "earliest"
    consumers:
      - name: "category-events"
        topic: "catalog.category.events"

security:
  token:
    public-key: "eb6ebefd6a2b0a304d43c2ccca329aef0a1439d429dbe8ca9b6190622ce38341"
    service-token: "v4.public.eyJleHAiOiIyMDM2LTAxLTE3VDE4OjMyOjAwKzAxOjAwIiwiaWF0IjoiMjAyNi0wMS0xOVQxODozMjowMCswMTowMCIsIm5iZiI6IjIwMjYtMDEtMTlUMTg6MzI6MDArMDE6MDAiLCJwZXJtaXNzaW9ucyI6WyJwcm9kdWN0czpyZWFkIiwiY2F0ZWdvcmllczpyZWFkIiwiYXR0cmlidXRlczpyZWFkIl0sInJvbGUiOiJzZXJ2aWNlX2FjY291bnQiLCJzZXJ2aWNlX25hbWUiOiJjYXRlZ29yeS1xdWVyeS1zZXJ2aWNlIiwic3ViIjoic2VydmljZTpjYXRlZ29yeS1xdWVyeS1zZXJ2aWNlIiwidHlwZSI6ImFjY2VzcyJ9NQkAT-p14r3S8EEk2bE8YBIxmej_SlErU7bE5XJNb48KekfUYIwtGAzCIQRdVvjCpSaNFyJ66T6_0_X3YJ9AAA"

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false
