logger:
  level: "debug"
  development: true

server:
  port: 8080

mongo:
  host: "mongo"
  port: 27017
  replica-set: rs0
  database: "category-query"
  migrations:
    enabled: true
    auto-migrate: true

kafka:
  brokers: "kafka:29092"
  schema-registry:
    url: "http://schema-registry:8081"
    auto-register-schemas: true
  consumers-config:
    default-group-id: "ecommerce-category-query-service"
    default-auto-offset-reset: "earliest"
    consumers:
      - name: "category-events"
        topic: "catalog.category.events"

clients:
  catalog-service:
    base-url: "http://ecommerce-catalog-service:8080"

security:
  token:
    public-key: "eb6ebefd6a2b0a304d43c2ccca329aef0a1439d429dbe8ca9b6190622ce38341"
    service-token: "v4.public.eyJleHAiOiIyMDM2LTAxLTE3VDE4OjI4OjEwKzAxOjAwIiwiaWF0IjoiMjAyNi0wMS0xOVQxODoyODoxMCswMTowMCIsIm5iZiI6IjIwMjYtMDEtMTlUMTg6Mjg6MTArMDE6MDAiLCJwZXJtaXNzaW9ucyI6WyJwcm9kdWN0czpyZWFkIiwiY2F0ZWdvcmllczpyZWFkIiwiYXR0cmlidXRlczpyZWFkIl0sInJvbGUiOiJzZXJ2aWNlX2FjY291bnQiLCJzZXJ2aWNlX25hbWUiOiJwcm9kdWN0LXF1ZXJ5LXNlcnZpY2UiLCJzdWIiOiJzZXJ2aWNlOnByb2R1Y3QtcXVlcnktc2VydmljZSIsInR5cGUiOiJhY2Nlc3MifdIGPYZc8BFBB4V4CrYHPtEn-7_YGZILmeEbjeB62ifAXl2R--OrrZOpJ3e3Sdm7P_RgMC4YCab-U6Wq5odOGw8"

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false
