logger:
  level: "debug"
  development: true

server:
  port: 8080

mongo:
  host: "mongo"
  port: 27017
  replica-set: rs0
  database: "category-query"
  migrations:
    enabled: true
    auto-migrate: true

kafka:
  brokers: "kafka:29092"
  schema-registry:
    url: "http://schema-registry:8081"
    auto-register-schemas: true
  consumers-config:
    default-group-id: "ecommerce-category-query-service"
    default-auto-offset-reset: "earliest"
    consumers:
      - name: "category-events"
        topic: "catalog.category.events"

clients:
  attribute-service:
    base-url: "http://ecommerce-attribute-service:8080"

security:
  public-key: "eb6ebefd6a2b0a304d43c2ccca329aef0a1439d429dbe8ca9b6190622ce38341"

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false
